[package]
name = "AsyncScheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
rand = "0.9.0-alpha.1"
mio = { version = "0.8.11", features = ["os-poll", "net"] }